# Generated by Django 2.2.13 on 2020-06-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200627_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='test',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
