# Generated by Django 2.2.13 on 2020-06-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_auto_20200627_0718"),
    ]

    operations = [
        migrations.AddField(
            model_name="customtext",
            name="dfgsdfgs",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customtext",
            name="eret",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customtext",
            name="hytryuryu",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
