# Generated by Django 2.2.13 on 2020-06-27 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_auto_20200627_0720"),
    ]

    operations = [
        migrations.RemoveField(model_name="customtext", name="dfgsdfgs",),
        migrations.RemoveField(model_name="customtext", name="eret",),
        migrations.RemoveField(model_name="customtext", name="hytryuryu",),
    ]
